name: Create Woodworking Toolkit Add-on Zip

on:
  push:
    branches:
      - main

#env:
  #VERSION: 0.1.${{ github.run_number }}  # default to avoid intellisense error
  #VERSION: ${{ format('{0:yy.MM.dd}', github.event.repository.pushed_at) }}.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permission to the GITHUB_TOKEN
    steps:     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Version
        id: versioning
        run: | 
          # generate local version in this step
          VERSION=$(date +'%y.%-m.%-d')".${{ github.run_number }}
          # create OUTPUT variables for next steps
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          PYTHON_VERSION=$(echo $VERSION | tr '.' ',')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in manifest and init file
        run: |
          VERSION=${{ steps.versioning.outputs.VERSION }}
          PYTHON_VERSION=${{ steps.versioning.outputs.PYTHON_VERSION }}
          sed -i "s/__VERSION__/$VERSION/" Add-ons/WoodworkingToolkit/blender_manifest.toml
          sed -i "s/version\": (.*/version\": ($PYTHON_VERSION),/" Add-ons/WoodworkingToolkit/__init__.py

      - name: Create zip file
        run: |
          cd Add-ons
          zip -r ../artifact.zip WoodworkingToolkit

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by GitHub
        with:
          tag_name: ${{ steps.versioning.outputs.VERSION }}
          release_name: Woodworking Toolkit v${{ steps.versioning.outputs.VERSION }}
          body: Release of Woodworking Toolkit v${{ steps.versioning.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: woodworking_toolkit_v${{ steps.versioning.outputs.VERSION }}.zip
          asset_content_type: application/zip